import 'package:flutter/material.dart';

// BRAND COLOR
const COLOR_BRAND_GREEN = Color(0xFF52BA31);
const COLOR_BRAND_GREEN_LIGHT = Color(0xFF8AD55D);
const COLOR_BRAND_GREEN_DARK = Color(0xFF0A8F0B);

// USE VARIATION FOR DARK AND GREYSH
const COLOR_BRAND_GREEN_GREY = Color(0xFF6C6052);
const COLOR_BRAND_GREEN_DARKEST = Color(0xFF265323);


// REDUNDAT USE AS MOVE AHEAD...
const COLOR_BRAND_VIOLET = Color(0xFF3E458E);
const COLOR_BG = Color(0xFFFFFFFF);
const COLOR_BG_GREY = Color(0xfff2f2f2);
const COLOR_BUTTON_ACTIVE = Color(0xFF3FA4BC);
const COLOR_BUTTON_INACTIVE = Color(0xFF3FA3BB);
const COLOR_BORDER = Color(0xFF3FA4BC);
const COLOR_ORANGE = Color(0xFFF3795D);
const COLOR_YELLOW = Color(0xFFFCF54E);
const COLOR_GREEN = Color(0xFF59CD78);
const COLOR_FONT_DEFAULT = Color(0xff000000);
const COLOR_ERROR_TEXT_COLOR = Color(0xff7c7c7c);
const COLOR_TEXT_BLUE = Color(0xff49a8bf);
const COLOR_FAB = Color(0xff49a8bf);
const COLOR_SPLASH_BG = Color(0xffDEEDEF);
const COLOR_TEXT_LABEL = Color(0xff7c7c7c);
const COLOR_PROFILE_TILE = Color(0xffd7d7d7);
const COLOR_PRE_FILLED_TEXT = Color(0xffECF6F8);
const COLOR_INPUT_FIELD = Color(0xffBFBFBF);
const COLOR_AUCTION_QUANTITY = Color(0xffD9343333);
const COLOR_APP_BAR = Color(0xffDEEDEF);
